feat: add support for client TLS certs
ory/k8s pull request #280
Opened 2021-06-15 21:21 UTC by christian-roggia

## Related issue

https://github.com/ory/oathkeeper/pull/744

2021-06-24 14:23 UTC, Demonsthere requested changes
Hello there! Thanks for the PR :) 
Got a few suggestions

2021-06-24 14:23 UTC, Demonsthere commented on helm/charts/oathkeeper/templates/deployment-controller.yaml
> +            secretName: {{- if .Values.certs.existingSecret }}
```suggestion
            secretName: {{- .Values.certs.existingSecret }}
```

2021-06-24 14:23 UTC, Demonsthere commented on helm/charts/oathkeeper/templates/deployment-controller.yaml
> +            name: {{ include "oathkeeper.name" . }}-config-demo
Please do not change this, and use `fullname`. This allows installation of multiple instances without resource overlapping.

2021-06-24 14:23 UTC, Demonsthere commented on helm/charts/oathkeeper/templates/deployment-controller.yaml
> +        - name: {{ include "oathkeeper.name" . }}-certs
```suggestion
        - name: {{ include "oathkeeper.fullname" . }}-certs
```

2021-06-24 14:23 UTC, Demonsthere commented on helm/charts/oathkeeper/templates/deployment-controller.yaml
> +            - name: {{ include "oathkeeper.name" . }}-certs
```suggestion
            - name: {{ include "oathkeeper.fullname" . }}-certs
```

2021-07-05 09:32 UTC, aeneasr requested changes
I think it would make sense to use the extraVolume pattern we have in Ory Kratos instead: https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml#L167-L179 :)

2021-07-07 17:26 UTC, christian-roggia commented
I can work on introducing that pattern

2021-07-12 12:24 UTC, aeneasr commented
As per https://github.com/ory/oathkeeper/pull/744#issuecomment-878235782 marking this as draft

2021-09-21 22:00 UTC, tobbbles commented
There's a hard and fast addition of extraVolume's at #330 -  I found myself to need it to get TLS certs into the pod :)

2021-09-22 06:57 UTC, Demonsthere commented
I'd say lets deprecate this PR in favour of #330. @christian-roggia are you ok with this?

2021-09-22 08:32 UTC, christian-roggia commented
Yes.

2021-09-22 08:33 UTC, closed without merging