feat: Update kratos chart for v6+
ory/k8s pull request #290
Opened 2021-06-28 11:40 UTC by Demonsthere

## Related issue

## Proposed changes

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2021-06-28 13:59 UTC, aeneasr requested changes

2021-06-28 13:59 UTC, aeneasr commented on .circleci/values/kratos.yaml
> +        memory: 2048MB
```suggestion
        memory: 128MB
```

2021-06-28 13:59 UTC, aeneasr commented on helm/charts/kratos/templates/deployment.yaml
> +            "/etc/config/meta/kratos.yaml"
```suggestion
            "/etc/config/kratos.yaml"
```

2021-06-28 13:59 UTC, aeneasr commented on helm/charts/kratos/templates/deployment.yaml
> +              mountPath: /etc/config/meta
```suggestion
              mountPath: /etc/config
```

2021-06-28 13:59 UTC, aeneasr commented on helm/charts/kratos/templates/statefulset-mail.yaml
> +              mountPath: /etc/config/meta
```suggestion
              mountPath: /etc/config
```

2021-06-28 13:59 UTC, aeneasr commented on helm/charts/kratos/templates/statefulset-mail.yaml
> +          args: [ "courier", "watch", "--config", "/etc/config/meta/kratos.yaml" ]
```suggestion
          args: [ "courier", "watch", "--config", "/etc/config/kratos.yaml" ]
```

2021-06-28 15:03 UTC, aeneasr commented
If it passes the CI it means it works right? 😅

2021-06-28 15:42 UTC, Demonsthere commented
right now the CI makes sure the chart can be installed, and that the applications are running afterwards (containers are not ins a crashloop, but running instead) 
Possible improvements:
- [ ] create some sort of healthcheck for the courier

2021-06-29 07:56 UTC, aeneasr approved these changes

2021-06-29 07:56 UTC, merged