feat: making all secret management across charts consistent
ory/k8s pull request #359
Opened 2021-10-31 15:41 UTC by ToonvanStrijp

## Related Issue or Design Document
#260 

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2021-10-31 15:42 UTC, ToonvanStrijp commented
@Demonsthere third time's a charm :100:

2021-11-02 13:08 UTC, Demonsthere requested changes
Hello there!
Just adding some finishing touches, but otherwise LGTM :)

2021-11-02 13:08 UTC, Demonsthere commented on helm/charts/hydra/values.yaml
> +  # nameOverride: "MyOtherName"
```suggestion
  # -- Provide custom name of existing secret, or custom name of secret to be created
  nameOverride: ""
  # nameOverride: "myCustomSecret"
```

2021-11-02 13:08 UTC, Demonsthere commented on helm/charts/hydra/values.yaml
> +  secretAnnotations:
```suggestion
  # -- Annotations to be added to secret. Annotations are added only when secret is being created. Existing secret will not be modified.,
  secretAnnotations:
```

2021-11-02 13:08 UTC, Demonsthere commented on helm/charts/oathkeeper/values.yaml
> +  # ... and choose a different name for a secret you provide like this
Please keep the comments consistent between charts ;) I have added suggestions in the first one

2021-11-02 14:37 UTC, ToonvanStrijp commented
@Demonsthere done :heavy_check_mark:

2021-11-03 09:09 UTC, Demonsthere requested changes
I think you missed something in oathkeeper ;) 
- https://github.com/ory/k8s/blob/master/helm/charts/oathkeeper/templates/deployment-controller.yaml#L57
- https://github.com/ory/k8s/blob/master/helm/charts/oathkeeper/templates/deployment-sidecar.yaml#L45
-

2021-11-04 08:08 UTC, Demonsthere approved these changes
All fine now! :)

2021-11-04 08:09 UTC, merged