Add support for overriding kratos deployment entrypoint (to allow sourcing DB credentials dynamically)
ory/k8s pull request #419
Opened 2022-03-22 12:48 UTC by eh-steve

Update kratos helm chart to allow overriding default entrypoint to support exporting environment variables using dynamic secrets.

The immediate use case is for getting a dynamic DB connection string issued by Hashicorp Vault, instead of a static kubernetes secret. 

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md)
      and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added necessary documentation within the code base (if
      appropriate).

## Further comments

2022-03-22 12:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/k8s?pullRequest=419) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/k8s?pullRequest=419) before we can accept your contribution.<br/><hr/>**Anonymous** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/k8s?pullRequest=419) it.</sub>

2022-03-22 14:59 UTC, Demonsthere requested changes
Hi there, thanks for the PR!

I see the benefit of such an option, but have some remarks. 
- For consistency, I'd prefer to include it in all charts, and not only one
- In charts that have several deployment objects (deployment/statefulset/jobs) it would be smart to have it per type
- I think a better naming convention would be `customComand` and `customArgs`

2022-03-22 14:59 UTC, Demonsthere commented on helm/charts/kratos/templates/deployment.yaml
> +          {{ if not (empty .Values.deployment.overrideArgs.command) }}
The check is redundant, you should be able to use just `if .Values.deployment.overrideArgs.command`

2022-03-22 14:59 UTC, Demonsthere commented on helm/charts/kratos/values.yaml
> +    command: []
Not sure if an array is a good idea here. For more complex scenarios, passing a multiline string like 
```yaml
command: |
  - some very complex
  - stuff that requires {{ .Values.other.stuff }}
```

and then calling `toYaml | tpl` might be better

2022-03-23 07:38 UTC, Demonsthere commented on helm/charts/kratos/values.yaml
> +    command: []
Please refer to the [Kartos chart](https://github.com/ory/k8s/blob/master/helm/charts/kratos/templates/deployment.yaml#L47-L51) how we handle similar parsing issues and how to [use it in values](https://github.com/ory/k8s/blob/master/.circleci/values/kratos.yaml#L83-L92)

2022-04-26 12:20 UTC, adamstrawson commented
Has there been any further progress on this? Looking to include the same behaviour in some other charts, and waiting for this to be completed so I can follow the same method for consistency.

2022-04-26 20:18 UTC, eh-steve commented
Sorry about that, we ended up implementing a few more changes in another working branch but forgot to bring them into this one - will update

2022-09-08 08:53 UTC, Demonsthere commented
Closing due to https://github.com/ory/k8s/pull/504 implementing similar feature set :)

2022-09-08 08:53 UTC, closed without merging