fix: Fix PDB indentation issue
ory/k8s pull request #656
Opened 2023-11-29 14:13 UTC by achedeuzot

I've fixed the PodDisruptionBudget yaml inclusion which would break files by setting fields at the root of the file.

## Related Issue or Design Document
On our  clusters, the helm charts create the following PDBs:

```
metadata:
  name: hydra
  namespace: hydra
minAvailable: 1 # This field is set here and is invalid.
spec:
  maxUnavailable: 25%
  selector:
    matchLabels:
      app.kubernetes.io/instance: hydra
      app.kubernetes.io/name: hydra
status:
```

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments
None

2023-11-30 07:53 UTC, Demonsthere reviewed
Hey there!
In order to properly fix this, please update the values in `hacks/values`, to enable PDB. This will force our CI to render the manifests and validate them. As PDB are optional objects we probably dont enable them by default and that is why this was omitted.

2023-11-30 15:57 UTC, achedeuzot commented
I've added the test values. They seem to show exactly one of the errors we had when trying to fix this: the default value is the following:
```
pdb:
  enabled: false
  spec:
    minAvailable: 1
```

When we specify the following:
```
pdb:
  enabled: true
  spec:
    maxUnavailable: 25%
```
The configuration that is computed it wrong, it merges the `spec` leading to 
```
pdb:
  enabled: true
  spec:
    minAvailable: 1
    maxUnavailable: 25%
```
which is not valid. Before my change, it used to work because the generated file would look like this:
```
pdb:
  enabled: true
  spec:
    maxUnavailable: 25%
minAvailable: 1 # Notice the ignored key here
```

How do you suggest I fix this ? I'm not sure what's the best approach ? Thanks !

2023-11-30 16:07 UTC, achedeuzot commented
One of the options is to use this instead of the `toYaml`:
```
  {{- if .Values.pdb.spec.maxUnavailable -}}
  maxUnavailable: {{ .Values.pdb.spec.maxUnavailable }}
  {{- else -}}
  minAvailable: {{ .Values.pdb.spec.minAvailable }}
  {{- end -}}
  ```

2023-11-30 16:20 UTC, Demonsthere commented
Since the PDB object has only 3 fields (selector, max and min) i think we can remove the `toYaml` and instead expose the fields implicit 

```yaml
spec:
  minAvailable: {{ .Values.pdb.spec.minAvailable }}
  maxUnavailable: {{ .Values.pdb.spec.maxUnavailable }}
```

2023-12-05 17:02 UTC, achedeuzot commented
You'll see I put a if/else because you can't specify both.
All checks should be green :) 
There's 1 failing check which is unrelated to this branch.

2023-12-05 17:03 UTC, achedeuzot commented
It should be ready to merge @Demonsthere ;)

2023-12-06 08:21 UTC, Demonsthere requested changes
Please run `make format` to make the CI happy :) 
I also would prefer a more explicit approach to the values

2023-12-06 08:21 UTC, Demonsthere commented on helm/charts/hydra-maester/templates/pdb.yaml
> +  minAvailable: {{ .Values.pdb.spec.minAvailable | default "1" }}
i dont like this hidden default value, maybe the following form would be more explicit?

```yaml
# values.yaml
pdb:
  enabled: true
  spec:
    maxUnavailable: ""
    minAvailable: ""
---
# template.yaml
{{- with .Values.pdb.spec.maxUnavailable }}
maxUnavailable: {{ . }}
{{- end }}
{{- with .Values.pdb.spec.minAvailable }}
minAvailable: {{ . }}
{{- end }}
```

I know the spec allows for only one field to be set, but `with` won't render empty fields, and imho it is the users responsibility to give sane data to the system

2023-12-11 15:06 UTC, achedeuzot commented
Hi @Demonsthere :)

I've replaced it with `with` instead of `if/else`, nice suggestion :D 

The `make format` doesn't seem to fix the docs file issue (which I haven't touched so it should be valid if it's valid on master... I don't get why the CI fails on a file that wasn't changed).

2023-12-12 09:43 UTC, Demonsthere approved these changes
Fixed the formatting, the error was on master branch 😓 
Thanks for the PR! :)

2023-12-12 09:43 UTC, merged