add support for using nodeport in kratos and kratos-selfservice-ui-no…
ory/k8s pull request #662
Opened 2024-01-09 09:54 UTC by leodotcloud

Resolves https://github.com/ory/k8s/issues/661

This PR enables use of NodePort service while deploying kratos and kratos-selfservice-ui-node helm charts.

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [x] I have referenced an issue containing the design document if my change introduces a new feature.
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security vulnerability.

2024-01-12 13:01 UTC, Demonsthere requested changes

2024-01-12 16:12 UTC, leodotcloud commented on helm/charts/kratos-selfservice-ui-node/templates/service.yaml
> +      {{- if and (eq .Values.service.type "NodePort") (not (eq .Values.service.nodePort nil)) }}
Good suggestion.

2024-01-12 16:21 UTC, leodotcloud commented
@Demonsthere, I updated the PR with the requested changes. Please check when you get a chance.

2024-01-15 07:40 UTC, Demonsthere approved these changes
Looks god now, thanks! :)

2024-01-15 07:40 UTC, merged