feat: upgrade kratos chart app version to 1.1.0
ory/k8s pull request #667
Opened 2024-02-28 18:55 UTC by parraletz

Upgrade kratos chart app version to  1.1.0

## Checklist

- [ x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ x] I have read the [security policy](../security/policy).
- [x ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.

## Further comments

2024-02-28 18:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ory/k8s?pullRequest=667) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ory/k8s?pullRequest=667) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ory/k8s?pullRequest=667) it.</sub>

2024-02-29 08:49 UTC, Demonsthere requested changes
Hi there! 
In order to bump the version of kratos we also need to change the image tag here: https://github.com/ory/k8s/blob/master/helm/charts/kratos/values.yaml#L18
Please update this and revert changes to `package-lock.json`, then we can merge this :)

2024-03-01 08:55 UTC, Demonsthere commented
Hi there! I see we have some more version bumps to do, so I gathered them in a single PR. We can close this in favour of https://github.com/ory/k8s/pull/668 if you dont mind 😉

2024-03-01 12:58 UTC, parraletz commented
Ok, dude, thanks! I'll close this PR in favour of https://github.com/ory/k8s/pull/668

2024-03-01 12:58 UTC, closed without merging