feat: allow dsn to be configured optionally
ory/k8s pull request #678
Opened 2024-05-13 14:13 UTC by dlahn

## Related Issue or Design Document

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

## Further comments

2024-05-14 08:04 UTC, Demonsthere requested changes
Great! :)
Can we add one test case for that? In the `hacks/values` directory we have the values.yaml that are used in our CI. I'd like this optional DSN option to be enabled for one one of the charts (so loaded from an external secret, the secret can be stored and loaded from here https://github.com/ory/k8s/tree/master/hacks/manifests)

2024-05-14 15:04 UTC, Demonsthere commented
I think we fall into https://github.com/helm/helm/issues/12438 here 😞 We can try with the `--force` option for upgrade, but if we fall into it, all users will :/

2024-05-14 16:54 UTC, dlahn commented
@Demonsthere Thanks for all of the help with the tests. It looks like it is all working now, and it matches how Hydra handles this.

2024-05-15 06:39 UTC, Demonsthere reviewed
Hi there!
Great job with the pr :) I would have a minot nitpick before we merge this: since now we see in the values for kratos what exactly needs to be modified to allow sideloading dsn, could you update the docs to show that? We could also link in the docs to the values files for kratos for a real life example!

2024-05-15 08:13 UTC, Demonsthere reviewed
updating docs :)

2024-05-15 08:40 UTC, Demonsthere approved these changes
lgtm!

2024-05-15 08:41 UTC, merged